[context.production.environment]
  GATSBY_SANITY_DATASET = "production"
  GATSBY_API_URI = "https://regen-registry-server.herokuapp.com"
  GATSBY_RECAPTCHA_SITE_KEY = "6LeqBFIaAAAAAPfLave4lUtLBKF2WYXinbaLNFqB"
  GATSBY_INTERCOM_APP_ID = "kn5di10s"

[context.deploy-preview.environment]
  GATSBY_SANITY_DATASET = "staging"
  GATSBY_API_URI = "https://regen-registry-server-staging.herokuapp.com"
  GATSBY_RECAPTCHA_SITE_KEY = "6LchxlAaAAAAANjtO3w4b5ihVCL87tYfbe0ltzp9"
  GATSBY_INTERCOM_APP_ID = "kn5di10s"

[context.hambach.environment]
  GATSBY_SANITY_DATASET = "staging"
  GATSBY_API_URI = "https://regen-registry-server-staging.herokuapp.com"
  GATSBY_RECAPTCHA_SITE_KEY = "6LchxlAaAAAAANjtO3w4b5ihVCL87tYfbe0ltzp9"
  GATSBY_INTERCOM_APP_ID = "kn5di10s"

[context.redwood.environment]
  GATSBY_SANITY_DATASET = "staging"
  GATSBY_API_URI = "https://regen-registry-server-staging.herokuapp.com"
  GATSBY_RECAPTCHA_SITE_KEY = "6LchxlAaAAAAANjtO3w4b5ihVCL87tYfbe0ltzp9"
  GATSBY_INTERCOM_APP_ID = "kn5di10s"

[build.environment]
  NODE_OPTIONS = "--max-old-space-size=10216"
